// Package models defines the database models for the Khamba Mobarak server.
package models

import (
	"crypto/rand"
	"encoding/hex"
	"time"

	"gorm.io/gorm"
)

// OfflineThreshold is how long a device can go without a heartbeat before it
// is considered offline / an outage is recorded. It defaults to 3x the
// firmware's heartbeat interval and can be overridden from config.Config at
// startup (see main.go).
var OfflineThreshold = 3 * time.Minute

// DisplayLocation is the timezone used to bucket daily outage summaries and
// compute "today/this month/this year" boundaries. Defaults to UTC; override
// from config.Config at startup.
var DisplayLocation = time.UTC

// Device represents a monitored device/location
type Device struct {
	ID        uint           `gorm:"primarykey" json:"id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`

	Name     string     `gorm:"size:100;not null" json:"name"`
	Location string     `gorm:"size:255" json:"location"`
	Token    string     `gorm:"size:64;uniqueIndex;not null" json:"-"`
	LastSeen *time.Time `json:"last_seen"`
	IsOnline bool       `gorm:"-" json:"is_online"` // Computed field
	Events   []Event    `gorm:"foreignKey:DeviceID" json:"events,omitempty"`
}

// Event represents a power event (boot or heartbeat)
type Event struct {
	ID        uint      `gorm:"primarykey" json:"id"`
	CreatedAt time.Time `json:"created_at"`

	DeviceID uint `gorm:"index;not null" json:"device_id"`
	// EventID is generated by the device and makes retries safe when a response is lost.
	EventID     string    `gorm:"size:64;index" json:"event_id"`
	EventType   string    `gorm:"size:20;not null" json:"event_type"`
	Timestamp   time.Time `gorm:"not null" json:"timestamp"`
	ResetReason string    `gorm:"size:64" json:"reset_reason,omitempty"`
}

// EventType constants
const (
	EventTypeBoot      = "boot"
	EventTypeHeartbeat = "heartbeat"
)

// GenerateToken creates a secure random token for device authentication
func GenerateToken() (string, error) {
	bytes := make([]byte, 32)
	if _, err := rand.Read(bytes); err != nil {
		return "", err
	}
	return hex.EncodeToString(bytes), nil
}

// IsDeviceOnline checks if a device is online based on last heartbeat.
// A device is considered online if it sent a heartbeat within OfflineThreshold.
func (d *Device) IsDeviceOnline() bool {
	if d.LastSeen == nil {
		return false
	}
	return time.Since(*d.LastSeen) < OfflineThreshold
}

// BeforeCreate hook to set computed fields
func (d *Device) AfterFind(tx *gorm.DB) error {
	d.IsOnline = d.IsDeviceOnline()
	return nil
}

// DailyOutageSummary stores aggregated outage counts per device per day.
// It is updated each time an outage is recorded.
type DailyOutageSummary struct {
	ID            uint      `gorm:"primarykey" json:"id"`
	DeviceID      uint      `gorm:"uniqueIndex:idx_device_date;not null" json:"device_id"`
	Date          time.Time `gorm:"uniqueIndex:idx_device_date;not null" json:"date"` // Truncated to midnight in DisplayLocation
	OutageCount   int       `gorm:"not null;default:0" json:"outage_count"`
	TotalDowntime int64     `gorm:"not null;default:0" json:"total_downtime"` // nanoseconds
}

// Outage is a retention-safe incident record. Cause is one of "connectivity"
// (gap inferred purely from a missed heartbeat), "power" (device reported a
// power-on/brownout reset), "device-reset" (device rebooted on its own while
// power was presumably fine), or "planned" (deep-sleep wake). Confidence is
// "inferred" or "confirmed" depending on whether a reset reason backed it up.
type Outage struct {
	ID             uint       `gorm:"primarykey" json:"id"`
	DeviceID       uint       `gorm:"index;not null" json:"device_id"`
	StartTime      time.Time  `gorm:"index;not null" json:"start_time"`
	EndTime        *time.Time `json:"end_time,omitempty"`
	Duration       int64      `gorm:"not null;default:0" json:"duration"`
	Cause          string     `gorm:"size:32;not null;default:connectivity" json:"cause"`
	Confidence     string     `gorm:"size:32;not null;default:inferred" json:"confidence"`
	Suppressed     bool       `gorm:"not null;default:false" json:"suppressed"`
	AcknowledgedAt *time.Time `json:"acknowledged_at,omitempty"`
	Notes          string     `gorm:"size:1000" json:"notes,omitempty"`
}

// DailyEventRollup preserves chart data after raw event retention expires.
type DailyEventRollup struct {
	ID         uint      `gorm:"primarykey"`
	DeviceID   uint      `gorm:"uniqueIndex:idx_rollup_device_date;not null"`
	Date       time.Time `gorm:"uniqueIndex:idx_rollup_device_date;not null"`
	Heartbeats int       `gorm:"not null;default:0"`
	Boots      int       `gorm:"not null;default:0"`
}

// MaintenanceWindow suppresses incidents caused by planned work.
type MaintenanceWindow struct {
	ID        uint      `gorm:"primarykey" json:"id"`
	DeviceID  *uint     `gorm:"index" json:"device_id,omitempty"`
	StartTime time.Time `gorm:"index;not null" json:"start_time"`
	EndTime   time.Time `gorm:"not null" json:"end_time"`
	Notes     string    `gorm:"size:1000" json:"notes"`
}

// OutageStats holds aggregated outage statistics for a device across different time windows.
type OutageStats struct {
	TodayCount    int           `json:"today_count"`
	TodayDowntime time.Duration `json:"today_downtime"`
	MonthCount    int           `json:"month_count"`
	MonthDowntime time.Duration `json:"month_downtime"`
	YearCount     int           `json:"year_count"`
	YearDowntime  time.Duration `json:"year_downtime"`
}

// OutageInfo represents information about a power outage.
// ID is 0 for a derived/ongoing outage that has no persisted Outage row yet
// (it cannot be acknowledged until the device recovers and the row is created).
type OutageInfo struct {
	ID             uint          `json:"id,omitempty"`
	DeviceID       uint          `json:"device_id"`
	DeviceName     string        `json:"device_name"`
	Location       string        `json:"location"`
	StartTime      time.Time     `json:"start_time"`
	EndTime        *time.Time    `json:"end_time,omitempty"`
	Duration       time.Duration `json:"duration"`
	IsOngoing      bool          `json:"is_ongoing"`
	Cause          string        `json:"cause"`
	Confidence     string        `json:"confidence"`
	Suppressed     bool          `json:"suppressed"`
	AcknowledgedAt *time.Time    `json:"acknowledged_at,omitempty"`
	Notes          string        `json:"notes,omitempty"`
}
